env: "paper"    # paper or live
timeframes:
  primary: "1min"
  confirm: "5min"
  trend: "15min"
ig:
  api_key: "177ab268b24734a7e44bf4d6ffff69fabe9a2ebf"
  username: "provaig123"
  password: "Demoqaz1!"
  account_type: "DEMO"   # DEMO or LIVE
risk:
  account_equity: 10000
  invest_per_trade: 1000
  max_loss_pct_invest: 6.0
  max_daily_loss_pct: 4.0
  max_losing_trades: 3
execution:
  time_in_force: "FILL_OR_KILL"
  use_trailing_stop: false  # Start with false for debugging
strategy:
  name: "ema_cross_breakout"
  params:
    fast: 9
    slow: 21
    atr_period: 14
    rr_take_profit: 1.5
symbols:
  # Start with just 1-2 liquid markets for testing
  - "CS.D.EURUSD.CFD.IP"   # EUR/USD - most liquid
  - "CS.D.GBPUSD.CFD.IP"   # GBP/USD - very liquid

  # Add more after you see it working:
  # - "IX.D.SPTRD.DAILY.IP"     # S&P 500
  # - "CS.D.CFEGOLD.CEB.IP"     # Gold

logging:
  level: "DEBUG"  # Use DEBUG to see everything
  sink: "logs/bot.log"
db:
  url: "sqlite:///bot.db"