env: "paper"    # paper or live
timeframes:
  primary: "1min"
  confirm: "5min"
  trend: "15min"
ig:
  api_key: "d73643a9e0d2672d848ca044f381f4ba4b6d112d"
  username: "ig_scalper_demo"
  password: "Demo.Scalper123!"
  account_type: "DEMO"   # DEMO or LIVE
risk:
  account_equity: 10000
  invest_per_trade: 1000
  max_loss_pct_invest: 6.0
  max_daily_loss_pct: 4.0
  max_losing_trades: 3
execution:
  time_in_force: "FILL_OR_KILL"
  use_trailing_stop: true
strategy:
  name: "ema_cross_breakout"
  params:
    fast: 9
    slow: 21
    atr_period: 14
    rr_take_profit: 1.5
symbols:
  # Major Forex Pairs (Most Likely to Work)
  - "CS.D.EURUSD.CFD.IP"
  #- "CS.D.GBPUSD.CFD.IP"
  #- "CS.D.USDJPY.CFD.IP"

  # Indices (Common EPICs - verify these)
  #- "IX.D.FTSE.DAILY.IP"      # FTSE 100 (changed from CFD.IP)
  #- "IX.D.DAX.DAILY.IP"       # DAX (changed from CFD.IP)
  #- "IX.D.SPTRD.DAILY.IP"     # S&P 500 (kept as is)

  # Try these alternatives if above don't work:
  # - "IX.D.NASDAQ.DAILY.IP"  # NASDAQ (try DAILY instead of CFD)
  # - "CS.D.GBPJPY.CFD.IP"    # GBP/JPY
  # - "CS.D.USCGC.IP"         # Gold (alternative)
  # - "CS.D.LCO.IP"           # Brent Crude (alternative to US Crude)
logging:
  level: "INFO"
  sink: "logs/bot.log"
db:
  url: "sqlite:///bot.db"
